import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderMenu from '../components/organisms/HeaderMenu'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <HeaderMenu></HeaderMenu>
      </main>
    </div>
  )
}
